/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RegistrationStatus } from './RegistrationStatus';
import {
    RegistrationStatusFromJSON,
    RegistrationStatusFromJSONTyped,
    RegistrationStatusToJSON,
} from './RegistrationStatus';

/**
 *
 * @export
 * @interface Registration
 */
export interface Registration {
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    trainingId: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    employeeId: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    employeeName: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    employeeEmail?: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    department?: string;
    /**
     *
     * @type {string}
     * @memberof Registration
     */
    note?: string;
    /**
     *
     * @type {RegistrationStatus}
     * @memberof Registration
     */
    status: RegistrationStatus;
    /**
     *
     * @type {Date}
     * @memberof Registration
     */
    registeredAt: Date;
}

/**
 * Check if a given object implements the Registration interface.
 */
export function instanceOfRegistration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "trainingId" in value;
    isInstance = isInstance && "employeeId" in value;
    isInstance = isInstance && "employeeName" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "registeredAt" in value;

    return isInstance;
}

export function RegistrationFromJSON(json: any): Registration {
    return RegistrationFromJSONTyped(json, false);
}

export function RegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Registration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': json['id'],
        'trainingId': json['trainingId'],
        'employeeId': json['employeeId'],
        'employeeName': json['employeeName'],
        'employeeEmail': !exists(json, 'employeeEmail') ? undefined : json['employeeEmail'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'status': RegistrationStatusFromJSON(json['status']),
        'registeredAt': (new Date(json['registeredAt'])),
    };
}

export function RegistrationToJSON(value?: Registration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'trainingId': value.trainingId,
        'employeeId': value.employeeId,
        'employeeName': value.employeeName,
        'employeeEmail': value.employeeEmail,
        'department': value.department,
        'note': value.note,
        'status': RegistrationStatusToJSON(value.status),
        'registeredAt': (value.registeredAt.toISOString()),
    };
}

