/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *
 * @export
 */
export const RegistrationStatus = {
    Registered: 'registered',
    Waitlisted: 'waitlisted'
} as const;
export type RegistrationStatus = typeof RegistrationStatus[keyof typeof RegistrationStatus];


export function RegistrationStatusFromJSON(json: any): RegistrationStatus {
    return RegistrationStatusFromJSONTyped(json, false);
}

export function RegistrationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationStatus {
    return json as RegistrationStatus;
}

export function RegistrationStatusToJSON(value?: RegistrationStatus | null): any {
    return value as any;
}

