/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegistrationInput
 */
export interface RegistrationInput {
    /**
     *
     * @type {string}
     * @memberof RegistrationInput
     */
    employeeId: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationInput
     */
    employeeName: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationInput
     */
    employeeEmail?: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationInput
     */
    department?: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationInput
     */
    note?: string;
    /**
     * Volitelny cielovy termin pri presune existujucej registracie.
     * @type {string}
     * @memberof RegistrationInput
     */
    targetTrainingId?: string;
}

/**
 * Check if a given object implements the RegistrationInput interface.
 */
export function instanceOfRegistrationInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "employeeId" in value;
    isInstance = isInstance && "employeeName" in value;

    return isInstance;
}

export function RegistrationInputFromJSON(json: any): RegistrationInput {
    return RegistrationInputFromJSONTyped(json, false);
}

export function RegistrationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'employeeId': json['employeeId'],
        'employeeName': json['employeeName'],
        'employeeEmail': !exists(json, 'employeeEmail') ? undefined : json['employeeEmail'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'note': !exists(json, 'note') ? undefined : json['note'],
        'targetTrainingId': !exists(json, 'targetTrainingId') ? undefined : json['targetTrainingId'],
    };
}

export function RegistrationInputToJSON(value?: RegistrationInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'employeeId': value.employeeId,
        'employeeName': value.employeeName,
        'employeeEmail': value.employeeEmail,
        'department': value.department,
        'note': value.note,
        'targetTrainingId': value.targetTrainingId,
    };
}

