/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TrainingStatus } from './TrainingStatus';
import {
    TrainingStatusFromJSON,
    TrainingStatusFromJSONTyped,
    TrainingStatusToJSON,
} from './TrainingStatus';
import type { TrainingType } from './TrainingType';
import {
    TrainingTypeFromJSON,
    TrainingTypeFromJSONTyped,
    TrainingTypeToJSON,
} from './TrainingType';

/**
 * 
 * @export
 * @interface TrainingInput
 */
export interface TrainingInput {
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    title: string;
    /**
     * 
     * @type {TrainingType}
     * @memberof TrainingInput
     */
    type: TrainingType;
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    department: string;
    /**
     * 
     * @type {Date}
     * @memberof TrainingInput
     */
    startAt: Date;
    /**
     * 
     * @type {number}
     * @memberof TrainingInput
     */
    capacity: number;
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    lecturer: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    location?: string;
    /**
     * Online link skolenia; prazdny retazec znamena, ze skolenie je prezencne.
     * @type {string}
     * @memberof TrainingInput
     */
    onlineLink?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof TrainingInput
     */
    requirements?: string;
    /**
     * 
     * @type {TrainingStatus}
     * @memberof TrainingInput
     */
    status: TrainingStatus;
}

/**
 * Check if a given object implements the TrainingInput interface.
 */
export function instanceOfTrainingInput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "department" in value;
    isInstance = isInstance && "startAt" in value;
    isInstance = isInstance && "capacity" in value;
    isInstance = isInstance && "lecturer" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function TrainingInputFromJSON(json: any): TrainingInput {
    return TrainingInputFromJSONTyped(json, false);
}

export function TrainingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrainingInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'type': TrainingTypeFromJSON(json['type']),
        'department': json['department'],
        'startAt': (new Date(json['startAt'])),
        'capacity': json['capacity'],
        'lecturer': json['lecturer'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'onlineLink': !exists(json, 'onlineLink') ? undefined : json['onlineLink'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'requirements': !exists(json, 'requirements') ? undefined : json['requirements'],
        'status': TrainingStatusFromJSON(json['status']),
    };
}

export function TrainingInputToJSON(value?: TrainingInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'type': TrainingTypeToJSON(value.type),
        'department': value.department,
        'startAt': (value.startAt.toISOString()),
        'capacity': value.capacity,
        'lecturer': value.lecturer,
        'location': value.location,
        'onlineLink': value.onlineLink,
        'description': value.description,
        'requirements': value.requirements,
        'status': TrainingStatusToJSON(value.status),
    };
}

