/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models';

/**
 * DepartmentsApi - interface
 * 
 * @export
 * @interface DepartmentsApiInterface
 */
export interface DepartmentsApiInterface {
    /**
     * Vrati zoznam oddeleni a odbornosti, pre ktore je mozne planovat skolenia.
     * @summary Zoznam oddeleni
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DepartmentsApiInterface
     */
    listDepartmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Vrati zoznam oddeleni a odbornosti, pre ktore je mozne planovat skolenia.
     * Zoznam oddeleni
     */
    listDepartments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>>;

}

/**
 * 
 */
export class DepartmentsApi extends runtime.BaseAPI implements DepartmentsApiInterface {

    /**
     * Vrati zoznam oddeleni a odbornosti, pre ktore je mozne planovat skolenia.
     * Zoznam oddeleni
     */
    async listDepartmentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/departments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Vrati zoznam oddeleni a odbornosti, pre ktore je mozne planovat skolenia.
     * Zoznam oddeleni
     */
    async listDepartments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listDepartmentsRaw(initOverrides);
        return await response.value();
    }

}
