/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xcervenkak@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Registration,
  RegistrationInput,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RegistrationFromJSON,
    RegistrationToJSON,
    RegistrationInputFromJSON,
    RegistrationInputToJSON,
} from '../models';

export interface CreateRegistrationRequest {
    trainingId: string;
    registrationInput: RegistrationInput;
}

export interface DeleteRegistrationRequest {
    trainingId: string;
    registrationId: string;
}

export interface GetRegistrationRequest {
    trainingId: string;
    registrationId: string;
}

export interface ListRegistrationsRequest {
    trainingId: string;
}

export interface UpdateRegistrationRequest {
    trainingId: string;
    registrationId: string;
    registrationInput: RegistrationInput;
}

/**
 * RegistrationsApi - interface
 *
 * @export
 * @interface RegistrationsApiInterface
 */
export interface RegistrationsApiInterface {
    /**
     * Vytvori registraciu zamestnanca a podla kapacity ho zaradi medzi prihlasenych alebo nahradnikov.
     * @summary Prihlasenie zamestnanca na skolenie
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {RegistrationInput} registrationInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationsApiInterface
     */
    createRegistrationRaw(requestParameters: CreateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>>;

    /**
     * Vytvori registraciu zamestnanca a podla kapacity ho zaradi medzi prihlasenych alebo nahradnikov.
     * Prihlasenie zamestnanca na skolenie
     */
    createRegistration(requestParameters: CreateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration>;

    /**
     * Odstrani registraciu zo skolenia a uvolni kapacitu dalsiemu nahradnikovi.
     * @summary Odhlasenie zo skolenia
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {string} registrationId Jedinecny identifikator registracie.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationsApiInterface
     */
    deleteRegistrationRaw(requestParameters: DeleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Odstrani registraciu zo skolenia a uvolni kapacitu dalsiemu nahradnikovi.
     * Odhlasenie zo skolenia
     */
    deleteRegistration(requestParameters: DeleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Vrati detail registracie konkretneho zamestnanca na skoleni.
     * @summary Detail registracie
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {string} registrationId Jedinecny identifikator registracie.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationsApiInterface
     */
    getRegistrationRaw(requestParameters: GetRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>>;

    /**
     * Vrati detail registracie konkretneho zamestnanca na skoleni.
     * Detail registracie
     */
    getRegistration(requestParameters: GetRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration>;

    /**
     * Vrati prihlasenych ucastnikov a nahradnikov pre konkretne skolenie.
     * @summary Zoznam registracii na skolenie
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationsApiInterface
     */
    listRegistrationsRaw(requestParameters: ListRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Registration>>>;

    /**
     * Vrati prihlasenych ucastnikov a nahradnikov pre konkretne skolenie.
     * Zoznam registracii na skolenie
     */
    listRegistrations(requestParameters: ListRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Registration>>;

    /**
     * Aktualizuje udaje registracie alebo presunie zamestnanca na iny termin pomocou targetTrainingId.
     * @summary Uprava registracie
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {string} registrationId Jedinecny identifikator registracie.
     * @param {RegistrationInput} registrationInput
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegistrationsApiInterface
     */
    updateRegistrationRaw(requestParameters: UpdateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>>;

    /**
     * Aktualizuje udaje registracie alebo presunie zamestnanca na iny termin pomocou targetTrainingId.
     * Uprava registracie
     */
    updateRegistration(requestParameters: UpdateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration>;

}

/**
 *
 */
export class RegistrationsApi extends runtime.BaseAPI implements RegistrationsApiInterface {

    /**
     * Vytvori registraciu zamestnanca a podla kapacity ho zaradi medzi prihlasenych alebo nahradnikov.
     * Prihlasenie zamestnanca na skolenie
     */
    async createRegistrationRaw(requestParameters: CreateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling createRegistration.');
        }

        if (requestParameters.registrationInput === null || requestParameters.registrationInput === undefined) {
            throw new runtime.RequiredError('registrationInput','Required parameter requestParameters.registrationInput was null or undefined when calling createRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainings/{trainingId}/registrations`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationInputToJSON(requestParameters.registrationInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationFromJSON(jsonValue));
    }

    /**
     * Vytvori registraciu zamestnanca a podla kapacity ho zaradi medzi prihlasenych alebo nahradnikov.
     * Prihlasenie zamestnanca na skolenie
     */
    async createRegistration(requestParameters: CreateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration> {
        const response = await this.createRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Odstrani registraciu zo skolenia a uvolni kapacitu dalsiemu nahradnikovi.
     * Odhlasenie zo skolenia
     */
    async deleteRegistrationRaw(requestParameters: DeleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling deleteRegistration.');
        }

        if (requestParameters.registrationId === null || requestParameters.registrationId === undefined) {
            throw new runtime.RequiredError('registrationId','Required parameter requestParameters.registrationId was null or undefined when calling deleteRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings/{trainingId}/registrations/{registrationId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))).replace(`{${"registrationId"}}`, encodeURIComponent(String(requestParameters.registrationId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Odstrani registraciu zo skolenia a uvolni kapacitu dalsiemu nahradnikovi.
     * Odhlasenie zo skolenia
     */
    async deleteRegistration(requestParameters: DeleteRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRegistrationRaw(requestParameters, initOverrides);
    }

    /**
     * Vrati detail registracie konkretneho zamestnanca na skoleni.
     * Detail registracie
     */
    async getRegistrationRaw(requestParameters: GetRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling getRegistration.');
        }

        if (requestParameters.registrationId === null || requestParameters.registrationId === undefined) {
            throw new runtime.RequiredError('registrationId','Required parameter requestParameters.registrationId was null or undefined when calling getRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings/{trainingId}/registrations/{registrationId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))).replace(`{${"registrationId"}}`, encodeURIComponent(String(requestParameters.registrationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationFromJSON(jsonValue));
    }

    /**
     * Vrati detail registracie konkretneho zamestnanca na skoleni.
     * Detail registracie
     */
    async getRegistration(requestParameters: GetRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration> {
        const response = await this.getRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vrati prihlasenych ucastnikov a nahradnikov pre konkretne skolenie.
     * Zoznam registracii na skolenie
     */
    async listRegistrationsRaw(requestParameters: ListRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Registration>>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling listRegistrations.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings/{trainingId}/registrations`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RegistrationFromJSON));
    }

    /**
     * Vrati prihlasenych ucastnikov a nahradnikov pre konkretne skolenie.
     * Zoznam registracii na skolenie
     */
    async listRegistrations(requestParameters: ListRegistrationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Registration>> {
        const response = await this.listRegistrationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktualizuje udaje registracie alebo presunie zamestnanca na iny termin pomocou targetTrainingId.
     * Uprava registracie
     */
    async updateRegistrationRaw(requestParameters: UpdateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Registration>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling updateRegistration.');
        }

        if (requestParameters.registrationId === null || requestParameters.registrationId === undefined) {
            throw new runtime.RequiredError('registrationId','Required parameter requestParameters.registrationId was null or undefined when calling updateRegistration.');
        }

        if (requestParameters.registrationInput === null || requestParameters.registrationInput === undefined) {
            throw new runtime.RequiredError('registrationInput','Required parameter requestParameters.registrationInput was null or undefined when calling updateRegistration.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainings/{trainingId}/registrations/{registrationId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))).replace(`{${"registrationId"}}`, encodeURIComponent(String(requestParameters.registrationId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationInputToJSON(requestParameters.registrationInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationFromJSON(jsonValue));
    }

    /**
     * Aktualizuje udaje registracie alebo presunie zamestnanca na iny termin pomocou targetTrainingId.
     * Uprava registracie
     */
    async updateRegistration(requestParameters: UpdateRegistrationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Registration> {
        const response = await this.updateRegistrationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
