/* tslint:disable */
/* eslint-disable */
/**
 * MedEdu API
 * API pre spravu katalogu internych skoleni nemocnicneho personalu.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kristian.cervenka@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Training,
  TrainingInput,
} from '../models';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    TrainingFromJSON,
    TrainingToJSON,
    TrainingInputFromJSON,
    TrainingInputToJSON,
} from '../models';

export interface CreateTrainingRequest {
    trainingInput: TrainingInput;
}

export interface DeleteTrainingRequest {
    trainingId: string;
}

export interface GetTrainingRequest {
    trainingId: string;
}

export interface ListTrainingsRequest {
    department?: string;
}

export interface UpdateTrainingRequest {
    trainingId: string;
    trainingInput: TrainingInput;
}

/**
 * TrainingsApi - interface
 * 
 * @export
 * @interface TrainingsApiInterface
 */
export interface TrainingsApiInterface {
    /**
     * Vytvori nove interne skolenie v katalogu.
     * @summary Vytvorenie skolenia
     * @param {TrainingInput} trainingInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApiInterface
     */
    createTrainingRaw(requestParameters: CreateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>>;

    /**
     * Vytvori nove interne skolenie v katalogu.
     * Vytvorenie skolenia
     */
    createTraining(requestParameters: CreateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training>;

    /**
     * Odstrani chybne vytvorene skolenie alebo pripravi endpoint pre jeho zrusenie v backende.
     * @summary Zrusenie alebo odstranenie skolenia
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApiInterface
     */
    deleteTrainingRaw(requestParameters: DeleteTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Odstrani chybne vytvorene skolenie alebo pripravi endpoint pre jeho zrusenie v backende.
     * Zrusenie alebo odstranenie skolenia
     */
    deleteTraining(requestParameters: DeleteTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Vrati detail jedneho skolenia podla identifikatora.
     * @summary Detail skolenia
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApiInterface
     */
    getTrainingRaw(requestParameters: GetTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>>;

    /**
     * Vrati detail jedneho skolenia podla identifikatora.
     * Detail skolenia
     */
    getTraining(requestParameters: GetTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training>;

    /**
     * Vrati vsetky dostupne skolenia vratane kapacity, obsadenosti a stavu.
     * @summary Zoznam skoleni
     * @param {string} [department] Volitelny filter podla oddelenia alebo odbornosti.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApiInterface
     */
    listTrainingsRaw(requestParameters: ListTrainingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Training>>>;

    /**
     * Vrati vsetky dostupne skolenia vratane kapacity, obsadenosti a stavu.
     * Zoznam skoleni
     */
    listTrainings(requestParameters: ListTrainingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Training>>;

    /**
     * Aktualizuje termin, kapacitu, lektora, miesto, popis, poziadavky alebo stav skolenia.
     * @summary Uprava skolenia
     * @param {string} trainingId Jedinecny identifikator skolenia.
     * @param {TrainingInput} trainingInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrainingsApiInterface
     */
    updateTrainingRaw(requestParameters: UpdateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>>;

    /**
     * Aktualizuje termin, kapacitu, lektora, miesto, popis, poziadavky alebo stav skolenia.
     * Uprava skolenia
     */
    updateTraining(requestParameters: UpdateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training>;

}

/**
 * 
 */
export class TrainingsApi extends runtime.BaseAPI implements TrainingsApiInterface {

    /**
     * Vytvori nove interne skolenie v katalogu.
     * Vytvorenie skolenia
     */
    async createTrainingRaw(requestParameters: CreateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>> {
        if (requestParameters.trainingInput === null || requestParameters.trainingInput === undefined) {
            throw new runtime.RequiredError('trainingInput','Required parameter requestParameters.trainingInput was null or undefined when calling createTraining.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingInputToJSON(requestParameters.trainingInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingFromJSON(jsonValue));
    }

    /**
     * Vytvori nove interne skolenie v katalogu.
     * Vytvorenie skolenia
     */
    async createTraining(requestParameters: CreateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training> {
        const response = await this.createTrainingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Odstrani chybne vytvorene skolenie alebo pripravi endpoint pre jeho zrusenie v backende.
     * Zrusenie alebo odstranenie skolenia
     */
    async deleteTrainingRaw(requestParameters: DeleteTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling deleteTraining.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings/{trainingId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Odstrani chybne vytvorene skolenie alebo pripravi endpoint pre jeho zrusenie v backende.
     * Zrusenie alebo odstranenie skolenia
     */
    async deleteTraining(requestParameters: DeleteTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTrainingRaw(requestParameters, initOverrides);
    }

    /**
     * Vrati detail jedneho skolenia podla identifikatora.
     * Detail skolenia
     */
    async getTrainingRaw(requestParameters: GetTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling getTraining.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings/{trainingId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingFromJSON(jsonValue));
    }

    /**
     * Vrati detail jedneho skolenia podla identifikatora.
     * Detail skolenia
     */
    async getTraining(requestParameters: GetTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training> {
        const response = await this.getTrainingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Vrati vsetky dostupne skolenia vratane kapacity, obsadenosti a stavu.
     * Zoznam skoleni
     */
    async listTrainingsRaw(requestParameters: ListTrainingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Training>>> {
        const queryParameters: any = {};

        if (requestParameters.department !== undefined) {
            queryParameters['department'] = requestParameters.department;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/trainings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrainingFromJSON));
    }

    /**
     * Vrati vsetky dostupne skolenia vratane kapacity, obsadenosti a stavu.
     * Zoznam skoleni
     */
    async listTrainings(requestParameters: ListTrainingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Training>> {
        const response = await this.listTrainingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktualizuje termin, kapacitu, lektora, miesto, popis, poziadavky alebo stav skolenia.
     * Uprava skolenia
     */
    async updateTrainingRaw(requestParameters: UpdateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Training>> {
        if (requestParameters.trainingId === null || requestParameters.trainingId === undefined) {
            throw new runtime.RequiredError('trainingId','Required parameter requestParameters.trainingId was null or undefined when calling updateTraining.');
        }

        if (requestParameters.trainingInput === null || requestParameters.trainingInput === undefined) {
            throw new runtime.RequiredError('trainingInput','Required parameter requestParameters.trainingInput was null or undefined when calling updateTraining.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/trainings/{trainingId}`.replace(`{${"trainingId"}}`, encodeURIComponent(String(requestParameters.trainingId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TrainingInputToJSON(requestParameters.trainingInput),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TrainingFromJSON(jsonValue));
    }

    /**
     * Aktualizuje termin, kapacitu, lektora, miesto, popis, poziadavky alebo stav skolenia.
     * Uprava skolenia
     */
    async updateTraining(requestParameters: UpdateTrainingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Training> {
        const response = await this.updateTrainingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
