/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KcrpMededuTrainingList {
        /**
          * @default ''
         */
        "apiBase": string;
    }
}
export interface KcrpMededuTrainingListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKcrpMededuTrainingListElement;
}
declare global {
    interface HTMLKcrpMededuTrainingListElementEventMap {
        "training-clicked": string;
        "training-create-clicked": void;
    }
    interface HTMLKcrpMededuTrainingListElement extends Components.KcrpMededuTrainingList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKcrpMededuTrainingListElementEventMap>(type: K, listener: (this: HTMLKcrpMededuTrainingListElement, ev: KcrpMededuTrainingListCustomEvent<HTMLKcrpMededuTrainingListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKcrpMededuTrainingListElementEventMap>(type: K, listener: (this: HTMLKcrpMededuTrainingListElement, ev: KcrpMededuTrainingListCustomEvent<HTMLKcrpMededuTrainingListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKcrpMededuTrainingListElement: {
        prototype: HTMLKcrpMededuTrainingListElement;
        new (): HTMLKcrpMededuTrainingListElement;
    };
    interface HTMLElementTagNameMap {
        "kcrp-mededu-training-list": HTMLKcrpMededuTrainingListElement;
    }
}
declare namespace LocalJSX {
    interface KcrpMededuTrainingList {
        /**
          * @default ''
         */
        "apiBase"?: string;
        "onTraining-clicked"?: (event: KcrpMededuTrainingListCustomEvent<string>) => void;
        "onTraining-create-clicked"?: (event: KcrpMededuTrainingListCustomEvent<void>) => void;
    }

    interface KcrpMededuTrainingListAttributes {
        "apiBase": string;
    }

    interface IntrinsicElements {
        "kcrp-mededu-training-list": Omit<KcrpMededuTrainingList, keyof KcrpMededuTrainingListAttributes> & { [K in keyof KcrpMededuTrainingList & keyof KcrpMededuTrainingListAttributes]?: KcrpMededuTrainingList[K] } & { [K in keyof KcrpMededuTrainingList & keyof KcrpMededuTrainingListAttributes as `attr:${K}`]?: KcrpMededuTrainingListAttributes[K] } & { [K in keyof KcrpMededuTrainingList & keyof KcrpMededuTrainingListAttributes as `prop:${K}`]?: KcrpMededuTrainingList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kcrp-mededu-training-list": LocalJSX.IntrinsicElements["kcrp-mededu-training-list"] & JSXBase.HTMLAttributes<HTMLKcrpMededuTrainingListElement>;
        }
    }
}
